spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/userDb
    username: embarkx
    password: embarkx
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

